### ISSUE TITLE
Post Issues Here

### ISSUE THREAD

**Issue by NickAnson** [willbkeller/automobile#1]
Are we doing something like 
                                               Econ -> components
                                               Sport -> higher quality components
and so on?

**Comment by willbkeller** [comment]
I would say something like that. I was thinking just having the type of car and then what components that would go with that car.
So:
Sport -> sport type components
Economy -> econ type components
etc.

If that makes any sense. That may be exactly what you're saying and I'm just wanting to clarify.

**Comment by willbkeller** [comment]
Hey guys, Anthony gave some advice and corrected how we should do our UML so if you look at wheel and tire I already added the properties to those. That said if you could maybe think about properties that would go with these categories and we could throw them in our UML tomorrow that would be great and we could split apart our project and get to writing code! I'll do what i can tonight and we will add in what you guys thing too. Also Anthony had us add a Towing category since we have four people in our group, and you'll see I added that in to the diagram.
Thanks guys!
@NickAnson @evanrivera @Wolfencode3000
![suspension component diagram - page 1-2](https://cloud.githubusercontent.com/assets/25177355/23637139/731e573c-029f-11e7-9820-7f6490eb359c.jpeg)

**Comment by NickAnson** [comment]
This is what i came up with
![uml autmobile - page 1](https://cloud.githubusercontent.com/assets/21188612/23693250/6570987c-0388-11e7-83e9-d8b866f080e3.png)

And i feel right between wheel and tire on sport model should be the type of sport then change depending on sport type

**Comment by Wolfencode3000** [comment]
Sorry guys, not going to be there this morning, feeling like crap from my cold.

**Comment by willbkeller** [comment]
@evanrivera heard you had a flat, no big deal. If we start coding today I'll let you know and let you know what you need to start doing, just check your  email every so often today.
@Wolfencode3000, alright thanks for letting us know i will keep you updated as well

**Comment by Wolfencode3000** [comment]
Looks like a good idea to combine shocks and springs together with the getheight variable. But im still confused on how we're to do this thing about the type of rim; forged, alloy, and something else.

**Comment by willbkeller** [comment]
@Wolfencode3000 @evanrivera We changed things up today so its along the lines of this now. Basically if you guys could, just look at the flow chart and get an idea of what is going on. This is what Nick and I worked on today and just kinda see what goes with what and get an idea of properties. Example: Sport->Lowered->short spring. stuff like that. Any questions just post them to here. Let me know when you guys get this so i know you're looking and working on it. Thanks!
![suspension component diagram - page 1-4](https://cloud.githubusercontent.com/assets/25177355/23716259/3239ec66-03f5-11e7-9359-c0a934fc49e5.jpeg)

**Comment by willbkeller** [comment]
honestly just write your thoughts down on paper and we can compare stuff tomorrow and hopefully finish this all up

**Comment by willbkeller** [comment]
Update on Uml:
![suspension component diagram - page 1-5](https://cloud.githubusercontent.com/assets/25177355/23736506/349289a2-0452-11e7-917f-1839c77b0d5e.jpeg)

**Comment by willbkeller** [comment]
@NickAnson @Wolfencode3000 @evanrivera

**Comment by willbkeller** [comment]
https://www.lucidchart.com/invitations/accept/19f0783e-e7ec-470f-8c97-63440c51a83d

**Comment by willbkeller** [comment]
Hey guys, Nick reformatted our repository to how it needs to be so I think you guys will need to pull my repository again so it matches up @Wolfencode3000  @evanrivera

**Comment by willbkeller** [comment]
Alright guys I guess this is it @NickAnson @Wolfencode3000 @evanrivera:
Suspension Component UML
![suspension component diagram - page 1](https://cloud.githubusercontent.com/assets/25177355/24023533/f79183c6-0a7a-11e7-9eaa-6f3d67834098.jpeg)

Wheel UML
![wheel - page 1](https://cloud.githubusercontent.com/assets/25177355/24023539/fe8faaea-0a7a-11e7-81fb-e903628cc19f.jpeg)

Tire UML
![tire - page 1](https://cloud.githubusercontent.com/assets/25177355/24023550/07536c0c-0a7b-11e7-9322-0836fc6ab97c.jpeg)

Shocks UML
![shocks - page 1](https://cloud.githubusercontent.com/assets/25177355/24023555/0ee2fe9c-0a7b-11e7-8337-ac80c059229b.jpeg)

Springs UML
![springs - page 1](https://cloud.githubusercontent.com/assets/25177355/24023562/18409814-0a7b-11e7-936b-2eb71b150572.jpeg)

Let me know who wants what out of Wheel/Tire/Spring/Shock ASAP so we can start coding

**Comment by evanrivera** [comment]
reforked new repository

**Comment by NickAnson** [comment]
Hey i'm working on these classes for the project 
![unnamed 1](https://cloud.githubusercontent.com/assets/21188612/24148018/e5da1416-0e0a-11e7-90fc-7ed77a884483.png)
![unnamed](https://cloud.githubusercontent.com/assets/21188612/24148019/e5e1cd82-0e0a-11e7-9457-77e79bc8c0f1.png)
![unnamed 2](https://cloud.githubusercontent.com/assets/21188612/24148020/e5e25040-0e0a-11e7-8784-2159fc63caa8.png)

**Comment by Wolfencode3000** [comment]
I got Economy and EconomySuspension done but about to head to afternoon classes then wont be home till almost 5 to finish up wheel.

**Comment by willbkeller** [comment]
sounds great! it looks pretty good I'm gonna review it later tonight

**Comment by NickAnson** [comment]
@willbkeller finished my tests if you want to look at em
